// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG6-AjosqGf2-4aN2g21jOVrf4wLiuOiM',
    appId: '1:457030797705:web:cefe97a40f1634e0de3958',
    messagingSenderId: '457030797705',
    projectId: 'quitmate-d8971',
    authDomain: 'quitmate-d8971.firebaseapp.com',
    storageBucket: 'quitmate-d8971.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8kHzfRa6AGnPJ3D_Yj51im4H9t9_m_vI',
    appId: '1:457030797705:android:8c69ce5da7a5ee05de3958',
    messagingSenderId: '457030797705',
    projectId: 'quitmate-d8971',
    storageBucket: 'quitmate-d8971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnFqM0Fx_SmV7iYrwCijtgpXaIAOmNsPI',
    appId: '1:457030797705:ios:5e7813c438e37859de3958',
    messagingSenderId: '457030797705',
    projectId: 'quitmate-d8971',
    storageBucket: 'quitmate-d8971.firebasestorage.app',
    iosBundleId: 'com.example.quitmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnFqM0Fx_SmV7iYrwCijtgpXaIAOmNsPI',
    appId: '1:457030797705:ios:5e7813c438e37859de3958',
    messagingSenderId: '457030797705',
    projectId: 'quitmate-d8971',
    storageBucket: 'quitmate-d8971.firebasestorage.app',
    iosBundleId: 'com.example.quitmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG6-AjosqGf2-4aN2g21jOVrf4wLiuOiM',
    appId: '1:457030797705:web:b25248cf79355851de3958',
    messagingSenderId: '457030797705',
    projectId: 'quitmate-d8971',
    authDomain: 'quitmate-d8971.firebaseapp.com',
    storageBucket: 'quitmate-d8971.firebasestorage.app',
  );
}
